<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 5.2.1
 */

/**
 * Database `zvuk-fm`
 */

/* `zvuk-fm`.`users` */
$users = array(
  array('id' => '27','email' => 'test-reklama1@yandex.ru','username' => 'testdictor','first_name' => 'Щербатюк Максим','city' => 'Курск','phone' => '+79107401846','company' => '','activity' => '1','password' => 'af41b3ddd766750c417dd4d1bf1d9efc83d41890e067ff5c53f246187a9016f1','utype_id' => '4','on_site' => '1','color' => '#6365e7','logins' => '6','last_login' => '1431765919','sum' => '0','img' => '/media/uploads/images/q7n2zr5atj6l.jpg','description' => 'Опытнейший универсальный диктор-баритон.','sample' => '/media/uploads/samples/voice.mp3','last_action' => '0','root_folder' => '','percent' => '100','position' => '1','doread' => '50','v_name' => 'Щербатюк','sms' => '0','is_ivr' => '1','ivr' => '/media/uploads/samples/ivr_scherbatyuktermosetprivetstvie1d_24.mp3','gender' => 'м','orderInP' => '0','email_verification' => '1'),
  array('id' => '34','email' => 'missvetik@mail.ru','username' => 'baranov-dik','first_name' => 'Баранов Эдуард','city' => 'Курск','phone' => '+79107401846','company' => '','activity' => '1','password' => '74105acdfc49e27aaad37f2e27b8268abbdb9deeca3b3cb4f744e236d02a2cf4','utype_id' => '4','on_site' => '0','color' => '','logins' => '0','last_login' => NULL,'sum' => '0','img' => '/media/uploads/images/1dg7mq6wkxt1.jpg','description' => 'Пожилой диктор с низким тембром. ','sample' => '/media/uploads/samples/baranov.mp3','last_action' => '0','root_folder' => '','percent' => '100','position' => '15','doread' => '50','v_name' => 'Баранов','sms' => '0','is_ivr' => '1','ivr' => '/media/uploads/samples/ivr_baranovavgustnprivetstvied_77-2-.mp3','gender' => 'м','orderInP' => '10','email_verification' => '1'),
  array('id' => '40','email' => 'epireklama4@gmail.com','username' => 'generalova','first_name' => 'Генералова Елена','city' => 'Курск','phone' => '+79606930003','company' => '','activity' => '1','password' => '230600921da59c42efcce1ba018acfa81fe2ef950ce3cc71a586f3cb8e1e3ef9','utype_id' => '4','on_site' => '0','color' => '','logins' => '1','last_login' => '1482920431','sum' => '0','img' => '/media/uploads/images/v456e49705p9.jpg','description' => 'Характерная актриса для игровых роликов.','sample' => '/media/uploads/samples/generalova.mp3','last_action' => '0','root_folder' => '','percent' => '0','position' => '4','doread' => '50','v_name' => 'Генералова','sms' => '0','is_ivr' => '1','ivr' => '/media/uploads/samples/ivr_generalovalantprivetstvie1y_476.mp3','gender' => 'ж','orderInP' => '4','email_verification' => '1'),
  array('id' => '41','email' => 'rezerv-pogoda@mail.ru','username' => 'olhovskiy','first_name' => 'Ольховский Алексей','city' => 'Белгород','phone' => '+70000000000','company' => '','activity' => '1','password' => '230600921da59c42efcce1ba018acfa81fe2ef950ce3cc71a586f3cb8e1e3ef9','utype_id' => '4','on_site' => '0','color' => '','logins' => '0','last_login' => NULL,'sum' => '0','img' => '/media/uploads/images/1re7zx7ozcu8.jpg','description' => 'Информационный диктор с приятным тембром.','sample' => '/media/uploads/samples/olhovsky-demo.mp3','last_action' => '0','root_folder' => '','percent' => '0','position' => '7','doread' => '50','v_name' => 'Ольховский','sms' => '0','is_ivr' => '1','ivr' => '/media/uploads/samples/ivr_olhovskiymasterkartprivetstvie1d_77-1-.mp3','gender' => 'м','orderInP' => '2','email_verification' => '1'),
  array('id' => '43','email' => 'audio-pogoda@epireklama.ru','username' => 'bazarov-maxim','first_name' => 'Базаров Максим','city' => 'Пермь','phone' => '+72222222222','company' => '','activity' => '1','password' => '230600921da59c42efcce1ba018acfa81fe2ef950ce3cc71a586f3cb8e1e3ef9','utype_id' => '4','on_site' => '0','color' => '','logins' => '0','last_login' => NULL,'sum' => '0','img' => '/media/uploads/images/bcsr3b4p60d6.jpg','description' => 'Молодёжный диктор для динамичных текстов. ','sample' => '/media/uploads/samples/bazarov-demo.mp3','last_action' => '0','root_folder' => '','percent' => '0','position' => '5','doread' => '50','v_name' => 'Базаров','sms' => '0','is_ivr' => '1','ivr' => '/media/uploads/samples/ivr_bazarovvashidengiprivetstvieiiizmy_506.mp3','gender' => 'м','orderInP' => '3','email_verification' => '1'),
  array('id' => '45','email' => 'nmsk-pogoda@mail.ru','username' => 'mikhailov-stasik','first_name' => 'Михайлов Стас','city' => 'Белгород','phone' => '+74444444444','company' => '','activity' => '1','password' => '74105acdfc49e27aaad37f2e27b8268abbdb9deeca3b3cb4f744e236d02a2cf4','utype_id' => '4','on_site' => '0','color' => '','logins' => '0','last_login' => NULL,'sum' => '0','img' => '/media/uploads/images/cye1gegrg6dt.jpg','description' => 'Дикторский голос для разноплановых роликов. ','sample' => '/media/uploads/samples/mikhailov.mp3','last_action' => '0','root_folder' => '','percent' => '0','position' => '9','doread' => '50','v_name' => 'Михайлов','sms' => '0','is_ivr' => '1','ivr' => '/media/uploads/samples/ivr_mihaylovregionalnyebesprovodnyesetiprivetstvie2d_77-1-.mp3','gender' => 'м','orderInP' => '6','email_verification' => '1'),
  array('id' => '46','email' => 'msk-pogoda@mail.ru','username' => 'nikitenko-olya','first_name' => 'Никитенко Ольга','city' => 'Курск','phone' => '+75555555555','company' => '','activity' => '1','password' => '74105acdfc49e27aaad37f2e27b8268abbdb9deeca3b3cb4f744e236d02a2cf4','utype_id' => '4','on_site' => '0','color' => '','logins' => '0','last_login' => NULL,'sum' => '0','img' => '/media/uploads/images/6vxu96x2tvgf.jpg','description' => 'Женский голос для информационных аудиороликов. ','sample' => '/media/uploads/samples/nikitenko.mp3','last_action' => '0','root_folder' => '','percent' => '0','position' => '10','doread' => '50','v_name' => 'Никитенко','sms' => '0','is_ivr' => '0','ivr' => '','gender' => 'ж','orderInP' => '9','email_verification' => '1'),
  array('id' => '47','email' => 'audio-pogoda@mail.ru','username' => 'androsov-tolik','first_name' => 'Андросов Анатолий','city' => 'Курск','phone' => '+76666666666','company' => '','activity' => '1','password' => '74105acdfc49e27aaad37f2e27b8268abbdb9deeca3b3cb4f744e236d02a2cf4','utype_id' => '4','on_site' => '0','color' => '','logins' => '2','last_login' => '1473952721','sum' => '0','img' => '/media/uploads/images/2poi79luofab.jpg','description' => 'Диктор для информационных роликов.','sample' => '/media/uploads/samples/androsov.mp3','last_action' => '0','root_folder' => '','percent' => '0','position' => '14','doread' => '50','v_name' => 'Андросов','sms' => '0','is_ivr' => '0','ivr' => '','gender' => 'м','orderInP' => '11','email_verification' => '1'),
  array('id' => '48','email' => 'text@zvuk.fm','username' => 'romashkin-sergio','first_name' => 'Ромашкин Сергей','city' => 'Курск','phone' => '+77777777777','company' => '','activity' => '1','password' => '74105acdfc49e27aaad37f2e27b8268abbdb9deeca3b3cb4f744e236d02a2cf4','utype_id' => '4','on_site' => '0','color' => '','logins' => '0','last_login' => NULL,'sum' => '0','img' => '/media/uploads/images/fxyi7aho63n5.jpg','description' => 'Диктор для персонажных и комичных роликов. ','sample' => '/media/uploads/samples/romashkin.mp3','last_action' => '0','root_folder' => '','percent' => '0','position' => '16','doread' => '50','v_name' => 'Ромашкин','sms' => '0','is_ivr' => '0','ivr' => '','gender' => 'м','orderInP' => '12','email_verification' => '1'),
  array('id' => '52','email' => 'oplata@zvuk.fm','username' => 'kovaleva-d','first_name' => 'Ковалёва Дарья','city' => 'Курск','phone' => '+71111111111','company' => '','activity' => '1','password' => 'af41b3ddd766750c417dd4d1bf1d9efc83d41890e067ff5c53f246187a9016f1','utype_id' => '4','on_site' => '0','color' => '#f07474','logins' => '7','last_login' => '1481735566','sum' => '0','img' => '/media/uploads/images/1qczhyjd7ki4.jpg','description' => 'Профессиональная актриса для разноплановых роликов
','sample' => '/media/uploads/samples/kovaleva.mp3','last_action' => '0','root_folder' => '','percent' => '30','position' => '6','doread' => '50','v_name' => 'Ковалёва','sms' => '0','is_ivr' => '1','ivr' => '/media/uploads/samples/ivr_kovalevasvarogprivetstvie1d_77.mp3','gender' => 'ж','orderInP' => '5','email_verification' => '1'),
  array('id' => '56','email' => 'audio.pogoda@gmail.com','username' => 'chernaya','first_name' => 'Черная Анастасия','city' => 'Тула','phone' => '+79107401846','company' => '','activity' => '1','password' => '230600921da59c42efcce1ba018acfa81fe2ef950ce3cc71a586f3cb8e1e3ef9','utype_id' => '4','on_site' => '0','color' => '','logins' => '0','last_login' => NULL,'sum' => '0','img' => '/media/uploads/images/ar3j240al6qb.jpg','description' => 'Сильная актриса для разноплановых роликов.','sample' => '/media/uploads/samples/chernaya-demo.mp3','last_action' => '0','root_folder' => '','percent' => '50','position' => '2','doread' => '50','v_name' => 'Черная','sms' => '0','is_ivr' => '1','ivr' => '/media/uploads/samples/ivr_chernayaavtomasterprivetstvie1y_400.mp3','gender' => 'ж','orderInP' => '1','email_verification' => '1'),
  array('id' => '57','email' => 'audio-pogoda@yandex.ru','username' => 'lukyanova','first_name' => 'Лукьянова Ольга','city' => 'Курск','phone' => '+79107401846','company' => '','activity' => '1','password' => '230600921da59c42efcce1ba018acfa81fe2ef950ce3cc71a586f3cb8e1e3ef9','utype_id' => '4','on_site' => '0','color' => '','logins' => '0','last_login' => NULL,'sum' => '0','img' => '/media/uploads/images/cshx4cyhk587.jpg','description' => 'Начинающий диктор для коротких информационных роликов','sample' => '/media/uploads/samples/demo-lukyanova-new.mp3','last_action' => '0','root_folder' => '','percent' => '30','position' => '8','doread' => '50','v_name' => 'Лукьянова','sms' => '0','is_ivr' => '0','ivr' => '','gender' => 'ж','orderInP' => '7','email_verification' => '1'),
  array('id' => '58','email' => 'demo-pogoda@mail.ru','username' => 'chalin','first_name' => 'Чалин Владислав','city' => '','phone' => '+79107401846','company' => '','activity' => '1','password' => '230600921da59c42efcce1ba018acfa81fe2ef950ce3cc71a586f3cb8e1e3ef9','utype_id' => '4','on_site' => '0','color' => '','logins' => '0','last_login' => NULL,'sum' => '0','img' => '/media/uploads/images/5jrqw8m7x88n.jpg','description' => 'Диктор с низким голосом. Отлично звучит в информационных роликах.','sample' => '/media/uploads/samples/chal-demo.mp3','last_action' => '0','root_folder' => '','percent' => '0','position' => '11','doread' => '100','v_name' => 'Чалин','sms' => '0','is_ivr' => '0','ivr' => '','gender' => 'м','orderInP' => '8','email_verification' => '1'),
  array('id' => '86','email' => 'text@epireklama.ru','username' => 'maximochka','first_name' => 'Максим','city' => 'Курск','phone' => '+73333333333','company' => '','activity' => '1','password' => '4eeb743fbe7b0d8efa5a845aa0c4d818e93bbc873482ff1b72eb328acf9ddfa3','utype_id' => '4','on_site' => '0','color' => '','logins' => '0','last_login' => NULL,'sum' => '0','img' => '/media/uploads/images/i1shkzapdpj4.jpg','description' => 'Детский голос. Дата рождения 20.09.2010.','sample' => '/media/uploads/samples/maxim-demo.mp3','last_action' => '0','root_folder' => '','percent' => '0','position' => '18','doread' => '50','v_name' => 'Максим','sms' => '0','is_ivr' => '0','ivr' => '','gender' => 'д','orderInP' => '14','email_verification' => '1'),
  array('id' => '107','email' => 'pogoda2konstruktor2@gmail.com','username' => 'Volkonsky','first_name' => 'Волконский Александр','city' => '','phone' => '+79107401846','company' => '','activity' => '1','password' => '4eeb743fbe7b0d8efa5a845aa0c4d818e93bbc873482ff1b72eb328acf9ddfa3','utype_id' => '4','on_site' => '0','color' => '','logins' => '0','last_login' => NULL,'sum' => '0','img' => '/media/uploads/images/rrkzehhnw8y7.jpg','description' => 'Сильный универсальный диктор с низким голосом. Озвучивает тексты хронометражем не более 55 секунд.','sample' => '/media/uploads/samples/volkonsky-demo.mp3','last_action' => '0','root_folder' => '','percent' => '0','position' => '3','doread' => '50','v_name' => 'Волконский','sms' => '0','is_ivr' => '1','ivr' => '/media/uploads/samples/ivr_volkonsky-demo.mp3','gender' => 'м','orderInP' => '0','email_verification' => '1'),
  array('id' => '172','email' => 'pogoda1@dipsa.ru','username' => 'seskov','first_name' => 'Еськов Сергей','city' => 'Курск','phone' => '+79999999999','company' => '','activity' => '1','password' => '230600921da59c42efcce1ba018acfa81fe2ef950ce3cc71a586f3cb8e1e3ef9','utype_id' => '4','on_site' => '0','color' => '','logins' => '0','last_login' => NULL,'sum' => '0','img' => '/media/uploads/images/g368e5hbvycv.jpg','description' => 'Диктор разноплановых задач.','sample' => '/media/uploads/samples/eskov-demo.mp3','last_action' => '0','root_folder' => '','percent' => '50','position' => '17','doread' => '50','v_name' => 'Еськов','sms' => '0','is_ivr' => '1','ivr' => '/media/uploads/samples/ivr_eskov-ivr.mp3','gender' => 'м','orderInP' => '13','email_verification' => '1'),
  array('id' => '219','email' => 'test-test@test.loc','username' => 'haritonov','first_name' => 'Харитонов Антон','city' => '','phone' => '+79107401846','company' => '','activity' => '1','password' => '7273819a7ee1b79136e626488fcd02b534db1f390aa755ffe36cb4a3178064af','utype_id' => '4','on_site' => '0','color' => '#34c3f0','logins' => '0','last_login' => NULL,'sum' => '0','img' => '','description' => 'Диктор с сильным голосом','sample' => '/media/uploads/samples/haritonov.mp3','last_action' => '0','root_folder' => '','percent' => '0','position' => '13','doread' => '0','v_name' => 'Харитонов','sms' => '0','is_ivr' => '1','ivr' => '/media/uploads/samples/ivr_ivr-demo-haritonov.mp3','gender' => 'м','orderInP' => '15','email_verification' => '1'),
  array('id' => '220','email' => 'gulidova@test.loc','username' => 'gulidovatest','first_name' => 'Гулидова Юлия','city' => 'Курск','phone' => '+79107401846','company' => '','activity' => '1','password' => '4eeb743fbe7b0d8efa5a845aa0c4d818e93bbc873482ff1b72eb328acf9ddfa3','utype_id' => '4','on_site' => '0','color' => '#d535d9','logins' => '0','last_login' => NULL,'sum' => '0','img' => '','description' => 'Актриса с низким голосом','sample' => '/media/uploads/samples/gulidova.mp3','last_action' => '0','root_folder' => '','percent' => '0','position' => '12','doread' => '0','v_name' => 'Гулидова','sms' => '0','is_ivr' => '0','ivr' => '','gender' => 'ж','orderInP' => '0','email_verification' => '1'),
  array('id' => '270','email' => 'audio-pogoda@apelsin.fm','username' => 'avrora10','first_name' => 'Аврора','city' => 'Курск','phone' => '+79107401846','company' => '','activity' => '1','password' => '4eeb743fbe7b0d8efa5a845aa0c4d818e93bbc873482ff1b72eb328acf9ddfa3','utype_id' => '4','on_site' => '0','color' => '#00fc38','logins' => '0','last_login' => NULL,'sum' => '0','img' => '/media/uploads/images/hmw7oud4wdhl.jpg','description' => 'Аврора. Детский голос 10 лет','sample' => '/media/uploads/samples/avrora.mp3','last_action' => '0','root_folder' => '','percent' => '50','position' => '19','doread' => '50','v_name' => 'Аврора','sms' => '0','is_ivr' => '0','ivr' => '','gender' => 'д','orderInP' => '59','email_verification' => '1')
);
